version: '3.8'

services:
  ltrack:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    image: ltrack:${LTRACK_VERSION:-latest}
    container_name: ltrack
    privileged: true  # Required for eBPF access
    volumes:
      - /sys/kernel/debug:/sys/kernel/debug:ro
      - /sys/fs/bpf:/sys/fs/bpf
      - /proc:/proc
      - /lib/modules:/lib/modules:ro
      - ltrack_logs:/var/log/ltrack
      - ../policy.toml:/app/external-config/policy.toml:ro
    environment:
      - LTRACK_LOG_LEVEL=info
      - LTRACK_LOG_FORMAT=json
    pid: host
    network_mode: host
    restart: unless-stopped

volumes:
  ltrack_logs:
    driver: local