# .github/workflows/test.yml
name: Tests Pipeline

# Only manual trigger on develop branch
on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of tests to run'
        type: choice
        required: true
        default: 'all'
        options:
        - all
        - unit
        - integration
        - benchmark
      debug_enabled:
        description: 'Enable debug mode'
        type: boolean
        required: false
        default: false

jobs:
  unit-tests:
    if: github.ref == 'refs/heads/develop' && (github.event.inputs.test_type == 'all' || github.event.inputs.test_type == 'unit')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm libelf-dev

      - name: Run Unit Tests
        run: go test -v -race -tags=unit ./...

      - name: Generate Coverage Report
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
          flags: unittests
          fail_ci_if_error: true

  integration-tests:
    if: github.ref == 'refs/heads/develop' && (github.event.inputs.test_type == 'all' || github.event.inputs.test_type == 'integration')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm libelf-dev

      - name: Run Integration Tests
        run: go test -v -tags=integration ./...

  benchmark-tests:
    if: github.ref == 'refs/heads/develop' && (github.event.inputs.test_type == 'all' || github.event.inputs.test_type == 'benchmark')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm libelf-dev

      - name: Run Benchmark Tests
        run: go test -v -bench=. -benchmem ./...

      - name: Store Benchmark Result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'go'
          output-file-path: benchmark.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '150%'
          comment-on-alert: true
          fail-on-alert: true

  test-summary:
    needs: [unit-tests, integration-tests, benchmark-tests]
    if: github.ref == 'refs/heads/develop' && always()
    runs-on: ubuntu-latest
    steps:
      - name: Check Test Results
        run: |
          if [ "${{ needs.unit-tests.result }}" != "success" ] || \
             [ "${{ needs.integration-tests.result }}" != "success" ] || \
             [ "${{ needs.benchmark-tests.result }}" != "success" ]; then
            echo "Some tests failed!"
            exit 1
          fi
          echo "All tests passed successfully!"